services:
  app:
    build: .
    image: najib-erp-php
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on: 
      - postgres
      - redis

  queue:
    image: najib-erp-php
    command: php artisan horizon
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis

  reverb:
    image: najib-erp-php
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    environment:
      - REVERB_HOST=0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: najib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
